<a href="https://colab.research.google.com/github/AbhishekMhamane/ml-learning/blob/main/numpy-exercises/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import numpy as np

In [65]:
# Creating arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[[1,2,3],[4,5,6]]])

print(a.ndim)
print(a)
print(b.ndim)
print(b)

arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
arrdim = arr.ndim
print("arr dimentions : {}".format(arrdim))


2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[[1 2 3]
  [4 5 6]]]
[[[[[1 2 3 4 5]]]]]
arr dimentions : 5


In [66]:
# Array indexing

arr = np.array([1,2,3,4,5,6,7])
print(arr[0])

print(a[1,1])
print(b[0,1,1])
print(a[1,-1])

# Array slicing

print(arr[1:3])
print(arr[3:])
print(arr[:3])
print(arr[-2:-1])
# arr[start:stop:step]
print(arr[1:5:2])

print(arr[::2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

1
5
5
6
[2 3]
[4 5 6 7]
[1 2 3]
[6]
[2 4]
[1 3 5 7]
[7 8 9]


In [67]:
# Data types

arr = np.array([1,2,3,4,5], dtype='i')
print(arr.dtype)
arr = np.array([1,2,3,4,5])
print(arr.dtype)

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

# Copy vs View
cparr = np.array([1.1, 2.1, 3.1])
x = cparr.copy()
y = cparr.view()
cparr[0] = 30
print(cparr)
print(x)
print(y)

y[2] = 100
print(cparr)
print(y)

print(x.base)
print(y.base)

int32
int64
[1 2 3]
int32
[30.   2.1  3.1]
[1.1 2.1 3.1]
[30.   2.1  3.1]
[ 30.    2.1 100. ]
[ 30.    2.1 100. ]
None
[ 30.    2.1 100. ]


In [68]:
# Array shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

# Array reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
newarr = arr.reshape(4, 3)
print(newarr)
print(newarr.ndim)

newarr = arr.reshape(2,3,2)
print(newarr)
print(newarr.ndim)
print(newarr.shape)


arr = np.array([1, 2, 3, 4])
newarr = arr.reshape(2, 2)
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [69]:
# Array iteration

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'
1
3
5
7
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [70]:
# Joining arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

# Splitting arrays

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

# Array searching

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

# Array sort
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

# Filtering array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[1 2]
[3 4]
[5 6]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
(array([3, 5, 6]),)
1
[0 1 2 3]
[False  True False  True False  True False]
[2 4 6]


In [71]:
# arange(start,end,step)
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)
arr = np.arange(1,10,2, dtype='complex')
print(arr)

# zeros
arr = np.zeros((3,3), dtype='int')
print(arr)
arr = np.zeros([3,4])
print(arr)

# ones
arr = np.ones((5,4), dtype='int')
print(arr)

# empty
arr = np.empty((3,3))
print(arr)

# linspace
arr = np.linspace(1,10,9)
print(arr)

# eye
arr = np.eye(3,3)
print(arr)

# random
x = np.random.randint(100)
print(x)
x = np.random.randint(100,size=(5))
print(x)

x = np.random.rand(5)
print(x)

x = np.random.randn(3)
print(x)

x = np.random.ranf(3)
print(x)

[1 2 3 4 5 6 7 8 9]
[1.+0.j 3.+0.j 5.+0.j 7.+0.j 9.+0.j]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4
[17 51 45 52 36]
[0.80585691 0.50279561 0.45433514 0.77143651 0.68236003]
[-0.00673223 -1.05427988 -1.13331233]
[0.0104923  0.83353398 0.60226379]


In [72]:
# flatten
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.flatten()
print(newarr)
newarr = arr.flatten('F')
print(newarr)

# ravel
newarr = arr.ravel()
print(newarr)
newarr = arr.ravel('F')
print(newarr)

# transpose
a = np.array([[1, 2], [3, 4], [5,6]])
print(a)
b = np.transpose(a)
print(b)

b = np.transpose(a, (0,1))
print(b)

b = np.transpose(b, (1,0))
print(b)

[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]
[1 4 2 5 3 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [73]:
# swapaxes
a = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(a)
b = np.swapaxes(a, 0, 1)
print(b)

# matrix
arr = np.matrix([[1, 2], [3, 4]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 1  2  3  4]
  [13 14 15 16]]

 [[ 5  6  7  8]
  [17 18 19 20]]

 [[ 9 10 11 12]
  [21 22 23 24]]]
[[1 2]
 [3 4]]


In [74]:
# linear algebra

# matrix inverse
arr = np.matrix([[1, 2], [3, 4]])
print(arr)
print(np.linalg.inv(arr))

# matrix power
print(np.linalg.matrix_power(arr, 2))
print(np.dot(arr,arr))

# linear equation (x + y = 10)
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
print(np.linalg.solve(a,b))

# determinant (ad - bc)
print(np.linalg.det(arr))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
[2. 3.]
-2.0000000000000004


In [75]:
# Mathematical ops
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(np.dot(arr1, arr2))
print(np.sum(arr1))
print(np.mean(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.argmin(arr1))
print(np.argmax(arr1))

# Broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20], [30]])
result = arr1 + arr2
print(result)

11
3
1.5
0.5
0.25
1
2
0
1
[[11 12 13]
 [21 22 23]
 [31 32 33]]
