<a href="https://colab.research.google.com/github/AbhishekMhamane/ml-learning/blob/main/numpy-exercises/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Creating arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[[1,2,3],[4,5,6]]])

print(a.ndim)
print(a)
print(b.ndim)
print(b)

arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
arrdim = arr.ndim
print("arr dimentions : {}".format(arrdim))


2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[[1 2 3]
  [4 5 6]]]
[[[[[1 2 3 4 5]]]]]
arr dimentions : 5


In [ ]:
# Array indexing

arr = np.array([1,2,3,4,5,6,7])
print(arr[0])

print(a[1,1])
print(b[0,1,1])
print(a[1,-1])

# Array slicing

print(arr[1:3])
print(arr[3:])
print(arr[:3])
print(arr[-2:-1])
# arr[start:stop:step]
print(arr[1:5:2])

print(arr[::2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

In [ ]:
# Data types

arr = np.array([1,2,3,4,5], dtype='i')
print(arr.dtype)
arr = np.array([1,2,3,4,5])
print(arr.dtype)

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

# Copy vs View
cparr = np.array([1.1, 2.1, 3.1])
x = cparr.copy()
y = cparr.view()
cparr[0] = 30
print(cparr)
print(x)
print(y)

y[2] = 100
print(cparr)
print(y)

print(x.base)
print(y.base)

In [ ]:
# Array shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

# Array reshape

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
newarr = arr.reshape(4, 3)
print(newarr)
print(newarr.ndim)

newarr = arr.reshape(2,3,2)
print(newarr)
print(newarr.ndim)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
